# Generated by Django 4.2.1 on 2023-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职时间'),
        ),
    ]
