# Generated by Django 4.2.1 on 2023-05-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userinfo_create_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
